# if  TARGET_ARCH == I386_ARCH || TARGET_ARCH == X86_64_ARCH || TARGET_ARCH == AARCH64_ARCH
/* Sun-$Revision: 1.3 $ */

/* Copyright 1992-2012 AUTHORS.
   See the LICENSE file for license information. */

# pragma implementation "stubs_amd64.hh"
# include "_stubs_amd64.cpp.incl"

# pragma warn_unusedarg off


// asm routines (only needed for SIC:)



extern "C" {
  oop UncommonBranch(...) { fatal("unimp intel");  return NULL; }
  // Note: do not have a stack frame yet; link is link of caller
  // Also, they must preserve Temp1 and Temp2
  }

// Only needed for interpreter/compiler interoperation:
extern "C" {  oop ReturnResult_stub(...) { fatal("unimp intel");  return NULL; } }
oop ReturnResult_stub_result;


# if TARGET_ARCH == AARCH64_ARCH && !defined(SIC_COMPILER)
// Interpreter-only build (SELF_INTERP_ONLY): the SIC compiler and its generated
// trapdoor stubs are absent, but shared runtime code still takes the address of
// the send-message stubs as markers (sendDesc::lookupRoutine, nlrSupport's
// fix_current_return_address, frame asserts). No compiled code is ever entered
// in this build, so these addresses are never jumped to; return a stable,
// unique, non-null sentinel that can never alias a real nmethod entry.
// -- interpreter-only build
static char aarch64_interp_only_send_stub[2] = { 0, 0 };
char* aarch64_SendMessage_stub()   { return &aarch64_interp_only_send_stub[0]; }
char* aarch64_SendDIMessage_stub() { return &aarch64_interp_only_send_stub[1]; }
# endif

# if TARGET_ARCH == X86_64_ARCH && !defined(SIC_COMPILER)
// Interpreter-only amd64 build: same sentinel scheme as aarch64 above.
static char amd64_interp_only_send_stub[2] = { 0, 0 };
char* amd64_SendMessage_stub()   { return &amd64_interp_only_send_stub[0]; }
char* amd64_SendDIMessage_stub() { return &amd64_interp_only_send_stub[1]; }
# endif

# if TARGET_ARCH == AARCH64_ARCH && defined(SIC_COMPILER)

extern "C" oop capture_NLR_parameters_from_registers(oop result,
                                                     smi target_frame,
                                                     int32 target_ID);
extern "C" {
  extern oop   NLRResultFromC;   // nlrSupport.cpp
  extern smi   NLRHomeFromC;
  extern int32 NLRHomeIDFromC;
}

// entry points handed to compiled senders whose send was interpreted by the
// VM (see sendDesc::sendMessage); set by generate_runtime_stubs_into
char* ReturnResult_entry = NULL;
char* ReturnNLR_entry    = NULL;

// EnterSelf: the C++ -> compiled-Self entry point.
//
// Generated into the stub zone at first use rather than written as static
// assembly: its inline sendDesc carries nmln words the runtime writes, and
// macOS text pages are immutable -- the JIT zone is the one writable+
// executable home.  Generating it also lets C++ supply the LookupType
// constant and lays the data block out via the same sendDesc offsets the
// compiler uses.
//
// The stub: builds a C frame record, saves the callee-saved registers
// compiled Self code may trash, reserves a Self outgoing area (lr hole at
// [sp+0], receiver at [sp+1], one argument at [sp+2]), and calls the
// nmethod.  Its return PC is the bottom-of-Self-stack sentinel
// (firstSelfFrame_returnPC) that frame walking terminates on, followed by
// the firstSelfFrame sendDesc.  An NLR arriving here behaves like a
// normal return (the result is already in x0).

oop (*EnterSelf_generated)(oop recv, char* entryPoint, oop arg1) = NULL;
oop (*EnterSelfN_generated)(oop recv, char* entryPoint, oop* args, int32 nargs) = NULL;
static char* SendMessage_stub_generated   = NULL;
static char* SendDIMessage_stub_generated = NULL;
static char* PrimBoundary_stub_generated  = NULL;

// Most args EnterSelfN marshals into its fixed outgoing area: the area is
// (EnterSelfMaxArgs + 2) words (lr hole + receiver + args).  Routing
// (route_to_nmethod in interpreter.cpp) must not enter compiled code for a
// send with more arguments than this -- keep that cap in sync.
extern const fint EnterSelfMaxArgs = 14; // extern: consts are internal by
                                         // default, and the debug build's
                                         // assert in EnterSelfN references it

// the trapdoor-resident lookup stub that empty/missed inline caches call
char* aarch64_SendMessage_stub() {
  assert(SendMessage_stub_generated != NULL,
         "runtime stubs are generated by the Trapdoors ctor at zone init");
  return SendMessage_stub_generated;
}

// the compiled-Self -> C-primitive boundary stub (see its generator below)
char* aarch64_PrimBoundary_stub() {
  assert(PrimBoundary_stub_generated != NULL,
         "runtime stubs are generated by the Trapdoors ctor at zone init");
  return PrimBoundary_stub_generated;
}

// ditto, for dynamic-inheritance parent-check misses
char* aarch64_SendDIMessage_stub() {
  assert(SendDIMessage_stub_generated != NULL,
         "runtime stubs are generated by the Trapdoors ctor at zone init");
  return SendDIMessage_stub_generated;
}

void generate_EnterSelf() {
  // kept for the lazy first_sendDesc() hook; generation actually happens
  // in the Trapdoors constructor (zone init), which precedes any send
  fatal("EnterSelf should have been generated at zone init");
}

// SendMessage_stub: reached through a send site's target word on an
// inline-cache miss.  On entry lr is the send's return PC, which IS the
// sendDesc; the receiver and arguments sit in the sender's outgoing area
// ([sp+1] up), and fp is the sender's frame.  Call the C lookup (which
// compiles and rebinds the cache), then tail-jump to the returned entry
// point with lr restored so the callee's prologue saves the right PC.
static void generate_SendMessage_stub(Assembler* a) {
  a->Comment("SendMessage_stub");
  a->sub(SP, SP, 16);
  a->stp(fp, lr, SP, 0);          // a real frame record: link + pc-in-sender
  a->mov(fp, SP);                 // x29 -> our record: C callees then link to
                                  //   it, so frame walks during the lookup
                                  //   find a proper callee record of the
                                  //   sender ([+0]=its fp, [+8]=send-site pc)
                                  //   instead of dead-ending on a C record
                                  //   whose return pc (this stub) is outside
                                  //   code->contains
  a->mov(x0, lr);                 // ic = the sendDesc
  a->mov(x1, SP);                 // lookupFrame = this record (frame* = record
                                  //   whose [+8] points into the sending method)
  a->ldr(x2, SP, 16 + 1*oopSize); // receiver from sender's outgoing area
  a->mov(x3, PerformSelectorLoc);  // dynamic selector (perform sends; x19)
  a->mov(x4, PerformDelegateeLoc); // dynamic delegatee (x20)
  a->ldr(x5, SP, 16 + 2*oopSize);  // arg1 from the outgoing area
  a->loadAddressLiteral(x16, (void*)&SendMessage, VMAddressOperand);
  a->blr(x16);
  a->mov(x17, x0);                // target entry point
  a->ldp(fp, lr, SP, 0);
  a->add(SP, SP, 16);
  a->br(x17);
}

// PrimBoundary: the compiled-Self -> C-primitive boundary.  Compiled code
// used to blr straight into the primitive, leaving the C compiler's own
// prologue to build the boundary frame record -- and WHERE that record
// lands is pure C-compiler convention: clang builds it at the TOP of the
// prim's frame (running_sp - 16), but gcc builds it at the BOTTOM, an
// entire prim frame lower.  Every walk that reaches a compiled frame with
// an outstanding prim call handles that record as the frame's stand-in
// (the +8 alias in Process::setWatermark, the {sp-16, sp-8} probes in
// PrimCallReturnTrap / get_patched_self_frame, patch_compiled_self_frame's
// return-slot write, save_outgoing_arguments' handle-relative reads), and
// all of it was calibrated against the clang position -- under gcc the
// record sits an unknowable frame-size away and those consumers read and
// write wild words (this sank the Linux/gcc tiered world build three
// different ways at three optimization levels).  Hand-building the record
// here pins the boundary geometry under every C compiler.  The ldp on the
// way out re-loads the possibly-patched return slot, so a
// PrimCallReturnTrap patch planted while the prim ran fires exactly as it
// did when the prim's own epilogue consumed the patched slot.
//   In: x16 = the primitive's C entry point (the site's target word),
//       lr = the site's return PC, x0..x7 = the marshaled C arguments.
//   Prims with stack-passed C arguments (nine or more) keep the direct
//   blr -- the 16-byte push here would shift their already-marshaled
//   stack arguments (see PrimNode::gen).
static void generate_PrimBoundary_stub(Assembler* a) {
  a->Comment("PrimBoundary");
  a->sub(SP, SP, 16);
  a->stp(fp, lr, SP, 0);   // canonical boundary record at running_sp - 16
  a->mov(fp, SP);          // the prim's own C record then chains to it
  a->blr(x16);
  a->ldp(fp, lr, SP, 0);   // lr = the return slot: the site's retPC, or the
  a->add(SP, SP, 16);      //   trap a mid-prim patch wrote into [record+8]
  a->ret();
}

// Entered from a DI desc when a compiled method's assignable-parent check
// fails (genHelper_aarch64.cpp verifyOneImmediateParent).  At that point
// the method has not yet built its frame: lr is still the send's return PC
// (= the sendDesc), sp points at the caller's outgoing area, x9 holds the
// count of parents already verified, and x10 the DIDesc reference point.
static void generate_SendDIMessage_stub(Assembler* a) {
  a->Comment("SendDIMessage_stub");
  a->sub(SP, SP, 16);
  a->stp(fp, lr, SP, 0);          // frame record: link + pc-in-sender
  a->mov(fp, SP);                 // x29 -> our record (see SendMessage_stub)
  a->mov(x0, lr);                 // ic = the sendDesc
  a->mov(x1, SP);                 // lookupFrame = this record
  a->mov(x2, Temp2);              // DIDesc* (x10)
  a->mov(x3, Temp1);              // count of verified parents (x9)
  a->ldr(x4, SP, 16 + 1*oopSize); // receiver from sender's outgoing area
  a->ldr(x5, SP, 16 + 2*oopSize); // arg1 (pad word for 0-arg sends)
  a->loadAddressLiteral(x16, (void*)&SendDIMessage, VMAddressOperand);
  a->blr(x16);
  a->mov(x17, x0);                // recompiled nmethod's entry point
  a->ldp(fp, lr, SP, 0);
  a->add(SP, SP, 16);
  a->br(x17);
}

int32 generate_runtime_stubs_into(char* dst, int32 avail) {
  ResourceMark rm;
  Assembler* saved = theAssembler;
  Assembler* a = theAssembler = new Assembler(1024, 64, false, true);

  // EnterSelf and EnterSelfN are two C entry points that converge on ONE
  // call+return-PC+epilogue, so frame walking keeps a single bottom-of-Self
  // sentinel (firstSelfFrame_returnPC).  Both build their own C frame and
  // reserve the SAME fixed-size Self outgoing area (lr hole + receiver + up to
  // EnterSelfMaxArgs args, 16-byte aligned); the shared epilogue drops that
  // one size.  EnterSelf marshals the 0/1-arg case (its legacy C signature);
  // EnterSelfN marshals nargs args from a C array.
  const fint kOutWords = EnterSelfMaxArgs + 2;            // lr hole + rcvr + args
  const fint kOutBytes = (kOutWords + (kOutWords & 1)) * oopSize;   // 16-aligned
  Label common(a->printing);
  Label done(a->printing);
  Label nlr_through(a->printing);

  // ---- EnterSelf(recv=x0, entryPoint=x1, arg1=x2): the 0/1-arg entry ----
  fint enterSelf_offset = a->offset();                   // == 0; EnterSelf_generated
  a->sub(SP, SP, 16);
  a->stp(fp, lr, SP, 0);
  a->mov(fp, SP);
  a->sub(SP, SP, 80);
  for (fint i = 0; i < 5; i++)
    a->stp(Location(x19 + 2*i), Location(x20 + 2*i), SP, 16*i);
  a->sub(SP, SP, kOutBytes);
  a->str(x0, SP, 1 * oopSize);       // receiver
  a->str(x2, SP, 2 * oopSize);       // the single argument (pad word for 0-arg)
  a->b(&common);

  // ---- EnterSelfN(recv=x0, entryPoint=x1, args=x2, nargs=x3): N-arg entry ----
  fint enterSelfN_offset = a->offset();
  a->sub(SP, SP, 16);
  a->stp(fp, lr, SP, 0);
  a->mov(fp, SP);
  a->sub(SP, SP, 80);
  for (fint i = 0; i < 5; i++)
    a->stp(Location(x19 + 2*i), Location(x20 + 2*i), SP, 16*i);
  a->sub(SP, SP, kOutBytes);
  a->mov(x14, SP);                   // GP copy of the outgoing-area base (SP can't
                                     //   be an add's source register directly)
  a->str(x0, x14, 1 * oopSize);      // receiver
  // marshal args[0..nargs-1] -> outgoing [base + (2+i) words]
  a->mov(x11, x3);                   // remaining count
  a->mov_imm(x9, 0);                 // running byte offset (i * oopSize)
  Label mloop(a->printing);
  Label mdone(a->printing);
  mloop.define();
  a->cbz(x11, &mdone);
  a->add(x12, x2, x9);               // &args[i]
  a->ldr(x10, x12, 0);
  a->add(x13, x14, x9);              // &base[i]
  a->str(x10, x13, 2 * oopSize);     // -> base + i*oopSize + 2 words
  a->add(x9, x9, oopSize);
  a->sub(x11, x11, 1);
  a->b(&mloop);
  mdone.define();
  // fall through to the shared call

  // ---- shared call + return point + sendDesc + epilogue ----
  common.define();
  // the return PC after blr must be 8-aligned (it is the sendDesc address)
  if (((a->offset() + 4) & 7) != 0) a->nop();
  a->blr(x1);

  fint retPC_offset = a->offset();
  a->b(&done);                       // @0  branch around desc; normal return
  a->Data((int32)0, false);          // @4  mask
  a->b(&nlr_through);                // @8  NLR entry
  a->Data((int32)0, false);          // @12 pad
  a->DataPtr(0);                     // @16 jump_address (never rebound)
  a->DataPtr(0);                     // @24 nmln next
  a->DataPtr(0);                     // @32 nmln prev
  a->DataPtr(0);                     // @40 selector (static lookup: unused)
  a->DataPtr(smi(StaticNormalLookupType));  // @48 lookupType
  fint descEnd_offset = a->offset();
  done.define();

  // epilogue: drop outgoing area, restore registers, return (result in x0)
  a->add(SP, SP, kOutBytes);
  for (fint i = 0; i < 5; i++)
    a->ldp(Location(x19 + 2*i), Location(x20 + 2*i), SP, 16*i);
  a->add(SP, SP, 80);
  a->ldp(fp, lr, SP, 0);
  a->add(SP, SP, 16);
  a->ret();

  // An NLR that propagates past the first Self frame must be recorded for
  // the C++ caller (sets _have_NLR_through_C and the *FromC globals) before
  // EnterSelf returns.  x0-x2 already hold result/home/homeID, matching the
  // C argument registers; the call returns the result in x0.
  nlr_through.define();
  a->loadAddressLiteral(x16, (void*)capture_NLR_parameters_from_registers,
                        VMAddressOperand);
  a->blr(x16);
  a->b(&done);

  a->align(8);
  fint sendMessage_offset = a->offset();
  generate_SendMessage_stub(a);

  a->align(8);
  fint sendDIMessage_offset = a->offset();
  generate_SendDIMessage_stub(a);

  a->align(8);
  fint primBoundary_offset = a->offset();
  generate_PrimBoundary_stub(a);

  // ReturnResult: a compiled sender's "callee" when the VM already
  // interpreted the send; just delivers the prepared result.
  a->Comment("ReturnResult");
  fint returnResult_offset = a->offset();
  a->loadAddressLiteral(x16, (void*)&ReturnResult_stub_result, VMAddressOperand);
  a->ldr(ResultReg, x16, 0);
  a->ret();

  // ReturnNLR: ditto, but an NLR escaped the interpreted callee; load the
  // NLR registers and divert to the send site's NLR entry (return PC + 8),
  // exactly like a compiled callee's NLR epilogue.
  a->Comment("ReturnNLR");
  fint returnNLR_offset = a->offset();
  a->loadAddressLiteral(x16, (void*)&NLRResultFromC, VMAddressOperand);
  a->ldr(NLRResultReg, x16, 0);
  a->loadAddressLiteral(x16, (void*)&NLRHomeFromC, VMAddressOperand);
  a->ldr(NLRHomeReg, x16, 0);
  a->loadAddressLiteral(x16, (void*)&NLRHomeIDFromC, VMAddressOperand);
  a->ldr32(NLRHomeIDReg, x16, 0);
  a->add(lr, lr, 8);
  a->ret();

  a->flushLiteralPool();   // &SendMessage literal; ldr-lit is pc-relative

  // copy into the trapdoor area (zone base, outside both the nmethod and
  // stub heaps -- so sendDesc::pic()/countStub() classify a freshly bound
  // lookup-routine target as 'none', exactly like i386's text-resident stubs)
  int32 len = a->instsLen();
  if (len > avail) fatal("trapdoor area too small for runtime stubs");
  {
    JITWriteScope ws;
    copy_bytes(a->instsStart, dst, len);
  }
  MachineCache::flush_instruction_cache_range(dst, dst + len);

  firstSelfFrame_returnPC   = dst + retPC_offset;
  firstSelfFrameSendDescEnd = dst + descEnd_offset;
  ReturnResult_entry        = dst + returnResult_offset;
  ReturnNLR_entry           = dst + returnNLR_offset;
  SendDIMessage_stub_generated = dst + sendDIMessage_offset;
  PrimBoundary_stub_generated  = dst + primBoundary_offset;
  EnterSelf_generated  = (oop (*)(oop, char*, oop))(dst + enterSelf_offset);
  EnterSelfN_generated = (oop (*)(oop, char*, oop*, int32))(dst + enterSelfN_offset);
  SendMessage_stub_generated = dst + sendMessage_offset;

  // finish the first sendDesc so it behaves like any virgin inline cache:
  // target = the lookup routine, dependency links self-initialized
  // (nmln::rebind splices unconditionally, so {NULL,NULL} links crash)
  sendDesc* f = sendDesc::sendDesc_from_return_PC(firstSelfFrame_returnPC);
  {
    JITWriteScope ws;
    f->set_jump_addr(SendMessage_stub_generated);
    f->dependency()->init();
  }

  // self-check: the generated block must parse as the first sendDesc
  assert(f->raw_lookupType() == StaticNormalLookupType,
         "generated firstSelfFrame sendDesc has wrong lookup type");
  assert((char*)f + f->endOffset() == firstSelfFrameSendDescEnd,
         "generated firstSelfFrame sendDesc has wrong size");

  theAssembler = saved;
  return len;
}

# endif // TARGET_ARCH == AARCH64_ARCH && defined(SIC_COMPILER)

# if TARGET_ARCH == X86_64_ARCH && defined(SIC_COMPILER)

// amd64 twin of the aarch64 section above.  Same structure and the same
// zone-resident stubs; x86 differences: CALL pushes the return PC (so the
// frame records come from the ordinary push rbp/mov rbp,rsp prologue and
// the sendDesc is found at [rsp] / [rbp+8], not in lr), the C ABI passes
// the first six arguments in rdi/rsi/rdx/rcx/r8/r9, and the descriptor
// layout is sendDesc_amd64.hh's (NLR entry at +5, mask at +10, target
// word at +16).

extern "C" oop capture_NLR_parameters_from_registers(oop result,
                                                     smi target_frame,
                                                     int32 target_ID);
extern "C" {
  extern oop   NLRResultFromC;   // nlrSupport.cpp
  extern smi   NLRHomeFromC;
  extern int32 NLRHomeIDFromC;
}

// entry points handed to compiled senders whose send was interpreted by the
// VM (see sendDesc::sendMessage); set by generate_runtime_stubs_into
char* ReturnResult_entry = NULL;
char* ReturnNLR_entry    = NULL;

// EnterSelf: the C++ -> compiled-Self entry point (see the aarch64 comment
// above; generated into the stub zone because its inline sendDesc carries
// nmln words the runtime writes).
oop (*EnterSelf_generated)(oop recv, char* entryPoint, oop arg1) = NULL;
oop (*EnterSelfN_generated)(oop recv, char* entryPoint, oop* args, int32 nargs) = NULL;
static char* SendMessage_stub_generated   = NULL;
static char* SendDIMessage_stub_generated = NULL;

// Most args EnterSelfN marshals into its fixed outgoing area: rcvr + up to
// EnterSelfMaxArgs args (the return PC is pushed by the CALL itself).
// Routing (route_to_nmethod in interpreter.cpp) must not enter compiled
// code for a send with more arguments than this -- keep that cap in sync.
extern const fint EnterSelfMaxArgs = 14;

// the trapdoor-resident lookup stub that empty/missed inline caches call
char* amd64_SendMessage_stub() {
  assert(SendMessage_stub_generated != NULL,
         "runtime stubs are generated by the Trapdoors ctor at zone init");
  return SendMessage_stub_generated;
}

// ditto, for dynamic-inheritance parent-check misses
char* amd64_SendDIMessage_stub() {
  assert(SendDIMessage_stub_generated != NULL,
         "runtime stubs are generated by the Trapdoors ctor at zone init");
  return SendDIMessage_stub_generated;
}

void generate_EnterSelf() {
  // kept for the lazy first_sendDesc() hook; generation actually happens
  // in the Trapdoors constructor (zone init), which precedes any send
  fatal("EnterSelf should have been generated at zone init");
}

// SendMessage_stub: reached through a send site's target word on an
// inline-cache miss.  On entry [rsp] is the send's return PC, which IS the
// sendDesc; the receiver and arguments sit in the sender's outgoing area
// ([rsp+8] up), and rbp is the sender's frame.  The ordinary prologue
// makes a proper frame record ({sender fp, send-site pc}) that frame
// walks during the lookup can traverse.  Call the C lookup (which
// compiles and rebinds the cache), then tail-jump to the returned entry
// point with [rsp] back at the sendDesc so the callee sees a fresh call.
static void generate_SendMessage_stub(Assembler* a) {
  a->Comment("SendMessage_stub");
  a->push(FrameReg);
  a->mov(FrameReg, SP);
  a->load(rdi, FrameReg, 1 * oopSize); // ic = the sendDesc (pushed retPC)
  a->mov(rsi, FrameReg);               // lookupFrame = this record
  a->load(rdx, FrameReg, 2 * oopSize); // receiver from sender's outgoing area
  a->mov(rcx, PerformSelectorLoc);     // dynamic selector (perform sends; r12)
  a->mov(r8,  PerformDelegateeLoc);    // dynamic delegatee (r13)
  a->load(r9, FrameReg, 3 * oopSize);  // arg1 from the outgoing area
  a->call_literal((void*)&SendMessage, VMAddressOperand);
  a->mov(Temp2, ResultReg);            // target entry point
  a->pop(FrameReg);                    // rsp -> the sendDesc retPC again
  a->jmp_reg(Temp2);
}

// Entered from a DI desc when a compiled method's assignable-parent check
// fails (genHelper_amd64.cpp verifyOneImmediateParent).  At that point the
// method has not yet built its frame: [rsp] is still the send's return PC
// (= the sendDesc), DICountReg holds the count of parents already
// verified, and DIInlineCacheReg the DIDesc reference point.
static void generate_SendDIMessage_stub(Assembler* a) {
  a->Comment("SendDIMessage_stub");
  a->push(FrameReg);
  a->mov(FrameReg, SP);
  a->load(rdi, FrameReg, 1 * oopSize); // ic = the sendDesc
  a->mov(rsi, FrameReg);               // lookupFrame = this record
  a->mov(rdx, DIInlineCacheReg);       // DIDesc* (r11)
  a->mov(rcx, DICountReg);             // count of verified parents (r10)
  a->load(r8, FrameReg, 2 * oopSize);  // receiver from sender's outgoing area
  a->load(r9, FrameReg, 3 * oopSize);  // arg1 (pad word for 0-arg sends)
  a->call_literal((void*)&SendDIMessage, VMAddressOperand);
  a->mov(Temp2, ResultReg);            // recompiled nmethod's entry point
  a->pop(FrameReg);
  a->jmp_reg(Temp2);
}

int32 generate_runtime_stubs_into(char* dst, int32 avail) {
  ResourceMark rm;
  Assembler* saved = theAssembler;
  Assembler* a = theAssembler = new Assembler(1024, 64, false, true);

  // EnterSelf and EnterSelfN are two C entry points that converge on ONE
  // call+return-PC+epilogue, so frame walking keeps a single bottom-of-Self
  // sentinel (firstSelfFrame_returnPC).  Both build their own C frame, save
  // the callee-saved registers compiled Self code may trash (rbx, r12-r15),
  // and reserve the SAME fixed-size Self outgoing area (receiver + up to
  // EnterSelfMaxArgs args, 16-byte aligned); the shared epilogue drops that
  // one size.  EnterSelf marshals the 0/1-arg case (its legacy C signature);
  // EnterSelfN marshals nargs args from a C array.
  const fint kOutWords = EnterSelfMaxArgs + 1;            // rcvr + args
  const fint kOutBytes = (kOutWords + (kOutWords & 1)) * oopSize;   // 16-aligned
  const fint kSaveBytes = 48;        // rbx + r12..r15, padded to 16
  Label common(a->printing);
  Label done(a->printing);
  Label nlr_through(a->printing);

  // ---- EnterSelf(recv=rdi, entryPoint=rsi, arg1=rdx): the 0/1-arg entry ----
  fint enterSelf_offset = a->offset();                   // == 0; EnterSelf_generated
  a->push(FrameReg);
  a->mov(FrameReg, SP);
  a->sub(SP, kSaveBytes);
  a->store(SP,  0, rbx);
  a->store(SP,  8, r12);
  a->store(SP, 16, r13);
  a->store(SP, 24, r14);
  a->store(SP, 32, r15);
  a->sub(SP, kOutBytes);
  a->store(SP, 0 * oopSize, rdi);    // receiver
  a->store(SP, 1 * oopSize, rdx);    // the single argument (pad word for 0-arg)
  a->jmp(&common);

  // ---- EnterSelfN(recv=rdi, entryPoint=rsi, args=rdx, nargs=rcx) ----
  fint enterSelfN_offset = a->offset();
  a->push(FrameReg);
  a->mov(FrameReg, SP);
  a->sub(SP, kSaveBytes);
  a->store(SP,  0, rbx);
  a->store(SP,  8, r12);
  a->store(SP, 16, r13);
  a->store(SP, 24, r14);
  a->store(SP, 32, r15);
  a->sub(SP, kOutBytes);
  a->store(SP, 0 * oopSize, rdi);    // receiver
  // marshal args[0..nargs-1] -> outgoing [sp + (1+i) words]
  a->mov_imm(Temp1, 0);              // running byte offset (i * oopSize)
  Label mloop(a->printing);
  Label mdone(a->printing);
  mloop.define();
  a->cmp(rcx, (fint)0);
  a->jcc(x64_e, &mdone);
  a->mov(rax, rdx);
  a->add(rax, Temp1);                // &args[i]
  a->load(Temp2, rax, 0);
  a->mov(rax, SP);
  a->add(rax, Temp1);                // &outgoing[i]
  a->store(rax, 1 * oopSize, Temp2); // -> sp + i*oopSize + 1 word
  a->add(Temp1, (fint)oopSize);
  a->sub(rcx, (fint)1);
  a->jmp(&mloop);
  mdone.define();
  // fall through to the shared call

  // ---- shared call + return point + sendDesc + epilogue ----
  common.define();
  // the return PC after the call must be 8-aligned (it is the sendDesc
  // address); call_reg(rsi) encodes in 2 bytes
  a->align_end(8, 2);
  a->call_reg(rsi);

  fint retPC_offset = a->offset();
  a->jmp(&done);                     // @0  branch around desc; normal return
  a->jmp(&nlr_through);              // @5  NLR entry
  a->Data((int32)0, false);          // @10 mask
  a->Short(0);                       // @14 pad
  a->DataPtr(0);                     // @16 jump_address (rebound below)
  a->DataPtr(0);                     // @24 nmln next
  a->DataPtr(0);                     // @32 nmln prev
  a->DataPtr(0);                     // @40 selector (static lookup: unused)
  a->DataPtr(smi(StaticNormalLookupType));  // @48 lookupType
  fint descEnd_offset = a->offset();
  done.define();

  // epilogue: drop outgoing area, restore registers, return (result in rax)
  a->add(SP, kOutBytes);
  a->load(rbx, SP,  0);
  a->load(r12, SP,  8);
  a->load(r13, SP, 16);
  a->load(r14, SP, 24);
  a->load(r15, SP, 32);
  a->add(SP, kSaveBytes);
  a->pop(FrameReg);
  a->ret();

  // An NLR that propagates past the first Self frame must be recorded for
  // the C++ caller (sets _have_NLR_through_C and the *FromC globals) before
  // EnterSelf returns.  Marshal the NLR registers (rax/rdx/rcx) into the C
  // argument registers; the call returns the result in rax.
  nlr_through.define();
  a->mov(rdi, NLRResultReg);         // rax
  a->mov(rsi, NLRHomeReg);           // rdx
  a->mov(rdx, NLRHomeIDReg);         // rcx (read after rsi <- old rdx)
  a->call_literal((void*)capture_NLR_parameters_from_registers,
                  VMAddressOperand);
  a->jmp(&done);

  a->align(8);
  fint sendMessage_offset = a->offset();
  generate_SendMessage_stub(a);

  a->align(8);
  fint sendDIMessage_offset = a->offset();
  generate_SendDIMessage_stub(a);

  // ReturnResult: a compiled sender's "callee" when the VM already
  // interpreted the send; just delivers the prepared result.
  a->Comment("ReturnResult");
  fint returnResult_offset = a->offset();
  a->loadAddressLiteral(Temp2, (void*)&ReturnResult_stub_result, VMAddressOperand);
  a->load(ResultReg, Temp2, 0);
  a->ret();

  // ReturnNLR: ditto, but an NLR escaped the interpreted callee; load the
  // NLR registers and divert to the send site's NLR entry, exactly like a
  // compiled callee's NLR epilogue (add the offset to the stacked retPC).
  a->Comment("ReturnNLR");
  fint returnNLR_offset = a->offset();
  a->loadAddressLiteral(Temp2, (void*)&NLRResultFromC, VMAddressOperand);
  a->load(NLRResultReg, Temp2, 0);
  a->loadAddressLiteral(Temp2, (void*)&NLRHomeFromC, VMAddressOperand);
  a->load(NLRHomeReg, Temp2, 0);
  a->loadAddressLiteral(Temp2, (void*)&NLRHomeIDFromC, VMAddressOperand);
  a->load32(NLRHomeIDReg, Temp2, 0);
  a->add_mem(SP, 0, sendDesc::non_local_return_offset);
  a->ret();

  a->flushLiteralPool();   // &SendMessage literal etc.; rip-relative

  // copy into the trapdoor area (zone base, outside both the nmethod and
  // stub heaps -- so sendDesc::pic()/countStub() classify a freshly bound
  // lookup-routine target as 'none', exactly like i386's text-resident stubs)
  int32 len = a->instsLen();
  if (len > avail) fatal("trapdoor area too small for runtime stubs");
  {
    JITWriteScope ws;
    copy_bytes(a->instsStart, dst, len);
  }
  MachineCache::flush_instruction_cache_range(dst, dst + len);

  firstSelfFrame_returnPC   = dst + retPC_offset;
  firstSelfFrameSendDescEnd = dst + descEnd_offset;
  ReturnResult_entry        = dst + returnResult_offset;
  ReturnNLR_entry           = dst + returnNLR_offset;
  SendDIMessage_stub_generated = dst + sendDIMessage_offset;
  EnterSelf_generated  = (oop (*)(oop, char*, oop))(dst + enterSelf_offset);
  EnterSelfN_generated = (oop (*)(oop, char*, oop*, int32))(dst + enterSelfN_offset);
  SendMessage_stub_generated = dst + sendMessage_offset;

  // finish the first sendDesc so it behaves like any virgin inline cache:
  // target = the lookup routine, dependency links self-initialized
  // (nmln::rebind splices unconditionally, so {NULL,NULL} links crash)
  sendDesc* f = sendDesc::sendDesc_from_return_PC(firstSelfFrame_returnPC);
  {
    JITWriteScope ws;
    f->set_jump_addr(SendMessage_stub_generated);
    f->dependency()->init();
  }

  // self-check: the generated block must parse as the first sendDesc
  assert(f->raw_lookupType() == StaticNormalLookupType,
         "generated firstSelfFrame sendDesc has wrong lookup type");
  assert((char*)f + f->endOffset() == firstSelfFrameSendDescEnd,
         "generated firstSelfFrame sendDesc has wrong size");

  theAssembler = saved;
  return len;
}

# endif // TARGET_ARCH == X86_64_ARCH && defined(SIC_COMPILER)

# endif // TARGET_ARCH == I386_ARCH || TARGET_ARCH == X86_64_ARCH || TARGET_ARCH == AARCH64_ARCH
